### ISSUE TITLE
三星手机运行Demo点击后面四个按钮直接闪退

### ISSUE THREAD

**Issue by code-rebooter** [catchpig/kmvvm#5]
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.catchpig.kmvvm/int}; have you declared this activity in your AndroidManifest.xml?
                                                                                                    	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2098)
                                                                                                    	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
                                                                                                    	at android.app.Activity.startActivityForResult(Activity.java:5473)
                                                                                                    	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
                                                                                                    	at android.app.Activity.startActivityForResult(Activity.java:5431)
                                                                                                    	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:560)
                                                                                                    	at android.app.Activity.startActivity(Activity.java:5817)
                                                                                                    	at android.app.Activity.startActivity(Activity.java:5770)
                                                                                                    	at com.catchpig.kmvvm.index.IndexFragment.onClick(IndexFragment.kt:25)

**Comment by catchpig** [comment]
已修复,请使用0.4.9版本
