### ISSUE TITLE
BaseFragment封装transaction.replace异常

### ISSUE THREAD

**Issue by MhuiHugh** [catchpig/kmvvm#9]
BaseFragment封装有个问题，默认使用方式1实现transaction.replace时抛出异常
//方式1 View newsView = inflater.inflate(R.layout.fragment_news, container);
//方式2 View newsView = inflater.inflate(R.layout.fragment_news, container,false);
https://www.jianshu.com/p/2989a927f5df

 java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                                                    	at android.view.ViewGroup.addViewInner(ViewGroup.java:5262)
                                                                                                    	at android.view.ViewGroup.addView(ViewGroup.java:5091)
                                                                                                    	at com.catchpig.mvvm.base.fragment.BaseFragment.onCreateView(BaseFragment.kt:104)

**Comment by MhuiHugh** [comment]
开了个不太优雅的补丁方式，先暂时解决问题
BaseFragment<VB : ViewBinding>(private val attachToRoot:Boolean=true, private val layoutId:Int=0) 
@LayoutRes int resource, @Nullable ViewGroup root, boolean attachToRoot
onCreateView()
 inflater.inflate(layoutId, container, false)

**Comment by MhuiHugh** [comment]
通过这种方式已解决
  val currentFragment = mFragmentList[position]
        if (currentFragment.isAdded) {
            transaction.show(currentFragment)
        } else {
            transaction.add(R.id.fl, currentFragment)
        }
        transaction.commitNow()
        //transaction.commit()

**Comment by catchpig** [comment]
已修复,请升级至1.0.5
